#+AUTHOR: Team 4
* Introduction

This guide provides instructions for installing and using a scanner generated by ANTLR4 using a Makefile.

* Linux Build Environment

This project's `antlr4>=4.11.1` generated code that can only be compiled with `clang++>=14.0.0`.

Recommended: Ubuntu22.04 is the development environment used for this project without any linking or compiling errors as the software repositories provide an up to date `clang++=14.0.0` through the command

#+begin_src 
sudo apt install clang
#+end_src

Although this can be used on other rolling-release linux distros like `arch`. 

* Prerequisites

The antlr4 and cpp versions are far ahead of what they usually are 

Before installing the scanner, you will need to have the following prerequisites: 

** Antlr CPP Runtime binary

This was the antlr4-cpp-runtime library used to build this project: https://www.antlr.org/download/antlr4-cpp-runtime-4.12.0-source.zip

Here is the tutorial to get it up and running on ubuntu: https:https://www.cs.sjsu.edu/~mak/tutorials/InstallANTLR4Cpp.pdf

All that is needed is the commands in `Download and install the C++ runtime for ANTLR` its subsection `Ubuntu installation` 


** Clang++ compiler:

Recommended: Ubuntu clang version 14.0.0-1ubuntu1

You will need `clang++>=14.0.0` to run this project. 

* Installation
To install the ANTLR4-generated scanner, follow these steps:

1. Download or clone the source code for the scanner.

2. Open a terminal and navigate to the directory where the source code is located.

3. Run the make command to compile the scanner code.

#+begin_src shell
make 
#+end_src

4. If the compilation is successful, the scanner executable will be

#+begin_src shell
./scanner
#+end_src

** Trouble shooting

If you get this error

#+begin_src 
./scanner: error while loading shared libraries: libantlr4-runtime.so.4.11.1: cannot open shared object file: No such file or directory
#+end_src
One quick work around in a linux environment is to use 

#+begin_src 
 export LD_LIBRARY_PATH=/usr/local/bin
#+end_src

This will make antlr4 unusable so make sure to exit the session after you are done using this project

* Usage
To use the scanner, follow these steps:

1. Create a text file containing the input text to be scanned.
2. Open a terminal and navigate to the directory where the scanner executable is located.
3. Run the scanner executable, passing the input file as a command-line argument. For example:

#+begin_src 
./scanner 
#+end_src

** Test Case 
The input is determined by the file [[file:test-in.txt]]. The scanner will read the input file and output the tokens it recognizes to the console. Simply change [[file:test-in.txt]] for the *master text case*
